Fixes #9903 feat(nimbus): Add UI for QA comments
mozilla/experimenter pull request #10012
Opened 2024-01-08 21:42 UTC by eliserichards

Because

- #9902 added a backend field for qa comments

This commit

- Adds the UI for qa comments

Fixes #9903 

----

<img width="1300" alt="Screenshot 2024-01-08 at 12 40 35 PM" src="https://github.com/mozilla/experimenter/assets/43795363/ea7592b1-f6ca-4327-8ed7-913ccee2e6a7">
<img width="1318" alt="Screenshot 2024-01-08 at 12 41 32 PM" src="https://github.com/mozilla/experimenter/assets/43795363/ad9960d1-57bf-4235-8717-26bc99213608">

2024-01-08 21:50 UTC, jaredlockhart requested changes
Yep all looks right and works right, one thing missing, doesn't display error if input is too long:

<img width="1220" alt="image" src="https://github.com/mozilla/experimenter/assets/119884/af5ddb77-e2ba-420b-9651-92eae95c3cb7">

2024-01-08 21:53 UTC, eliserichards commented
Gah! good catch 😛

2024-01-08 22:23 UTC, eliserichards commented
Done! and it also wordwraps now (I forgot that too)

<img width="1296" alt="Screenshot 2024-01-08 at 2 05 14 PM" src="https://github.com/mozilla/experimenter/assets/43795363/980bd2b1-7500-48d6-844d-e4ae573c2e85">

<img width="1304" alt="Screenshot 2024-01-08 at 2 21 58 PM" src="https://github.com/mozilla/experimenter/assets/43795363/b5803a20-c5cb-4949-8b22-0d488258cb7a">

2024-01-09 18:40 UTC, jaredlockhart commented
Ah another one, should be able to save the flag without a comment I think?

<img width="1261" alt="image" src="https://github.com/mozilla/experimenter/assets/119884/730a79e8-091e-477d-b53b-b63e0c84096c">

2024-01-09 22:05 UTC, eliserichards commented
Bah! Needed `allow_null=True` in addition to `allow_blank=True`

2024-01-10 17:47 UTC, jaredlockhart approved these changes
Yep all seems good, this is awesome thnx @eliserichards 🎉 🎉 🎉

2024-01-10 18:33 UTC, merged