Indicate that results are not available for rollouts
mozilla/experimenter pull request #10083
Opened 2024-01-20 12:04 UTC by nox1134

Because

-  The results button for rollouts is disabled while the help text incorrectly states "Experiment analysis not ready yet."

This commit

- Changes the help text to "Analysis results are not available for rollouts." clarifying that no results will ever appear.

Fixes #9766

2024-01-22 16:13 UTC, jaredlockhart requested changes
Thanks for taking this on @nox1134 !  You'll want to add a check whether to show the rollout message, but otherwise this should be good!

2024-01-22 16:13 UTC, jaredlockhart commented on experimenter/experimenter/nimbus-ui/src/components/AppLayoutSidebarLaunched/index.tsx
> +                      Analysis results are not available for rollouts.
Oh you'll want to actually check if it's a rollout here.  It's an experiment then `Experiment analysis not ready yet` is correct, but if we land here and it's a rollout then the new message is correct.

2024-01-22 16:14 UTC, jaredlockhart commented on experimenter/experimenter/nimbus-ui/src/components/AppLayoutSidebarLaunched/index.test.tsx
> +      });
And then you'd want two versions of this test, one for the rollout case, one for the experiment case.

2024-01-30 21:15 UTC, jaredlockhart approved these changes
Oh fantastic, thank you for wrapping this up @nox1134 🎉 🎉 🎉 🎉  Tested locally, works perfectly 🙏

2024-01-30 21:34 UTC, merged

2024-01-31 20:15 UTC, nox1134 commented
Thank you @jaredlockhart for your help!