feat(nimbus) Make branch screenshots linkable (#10365)
mozilla/experimenter pull request #10368
Opened 2024-03-05 22:23 UTC by dmose

Because

- The Skylight app wants to be able to link directly to the screenshots in the branch summary of an experiment

This commit 

- makes the screenshots section of each branch summary visibly linkable

Fixes #10365

2024-03-05 22:45 UTC, dmose commented
I've put the hashtag link affordance after the word "Screenshots", analogous to the one after "Recipe JSON".  Putting it before (as with the branch names) makes it appear as though it might be another branch.

<img width="924" alt="Bildschirmfoto 2024-03-05 um 2 43 18 PM" src="https://github.com/mozilla/experimenter/assets/425657/9285accb-bf45-4297-a4fc-4d8c9b0f18ac">

2024-03-06 01:55 UTC, yashikakhurana commented
@dmose just curious will it be possible there will be multiple screenshots?

2024-03-06 14:36 UTC, dmose commented
@yashikakhurana I assumed that there could be because the existing TableBranches code supports an array of screenshots and uses the word "Screenshots" in the UI for each branch. I don't know how frequently more than one screenshot is actually used. Maybe that's easy to check by looking at the prod database?

2024-03-06 15:27 UTC, brennie requested changes

2024-03-06 15:27 UTC, brennie commented on experimenter/experimenter/nimbus-ui/src/components/Summary/TableBranches/index.test.tsx
> +    );
We should have warnings for this but we don't. Please use react testing library for this.

```suggestion
    const screenshotsAnchors = screen.getAllByTestId("branch-screenshots-anchor");
    
    expect(screenshotsAnchors).toHaveLength(3);
    expect(screenshotsAnchors[0]).toHaveAttribute("id", screenshotsAnchorId)
    expect(screenshotsAnchors[0]).toHaveAttribute(
      "href",
      `#${screenshotsAnchorId}`,
    );
```

getAllByTestId will throw if there are no results, so we don't need to assert on its return.

2024-03-06 17:15 UTC, brennie approved these changes

2024-03-06 17:16 UTC, brennie commented
LGTM thanks!

2024-03-06 17:47 UTC, merged

2024-03-07 15:14 UTC, rfambro commented
Thanks Dan!