feat(nimbus): persist theme switcher in new nimbus ui
mozilla/experimenter pull request #10791
Opened 2024-06-03 21:56 UTC by jaredlockhart

Because

* We are implementing the new Nimbus UI in bootstrap 5 which supports light/dark themes
* We can add a toggle to switch themes
* We should persist the chosen theme

This commit

* Persists the chosen theme in localstorage
* Defaults to system light/dark theme

fixes #10685

https://github.com/mozilla/experimenter/assets/119884/cd8539dc-48fd-42e2-adf6-1b886c94d355

2024-06-03 23:00 UTC, brennie requested changes

2024-06-03 23:00 UTC, brennie commented on experimenter/experimenter/nimbus_ui_new/templates/experimenter_base.html
> +          setStoredTheme(theme);
Should setTheme called setStoredTheme?

2024-06-04 20:26 UTC, jaredlockhart commented
@brennie Okay ya good points, let's do this then.  I'll set up better static asset management in https://github.com/mozilla/experimenter/issues/10708 and then we can do as you say, move this to a script, lint it, stick it in the static build pipeline, etc.  So I'll mark this as blocked until I get that stuff in next.

2024-06-12 21:14 UTC, jaredlockhart commented
We'll be able to rebase this after https://github.com/mozilla/experimenter/pull/10834 lands

2024-06-13 18:59 UTC, brennie approved these changes
awesome, this is great with the new bundling stuff

2024-06-13 18:59 UTC, jaredlockhart commented
Ya so easy to just add a little page specific script 🙏

2024-06-13 19:23 UTC, merged