bug(nimbus): Redirect to correct review URL for prefFlips experiments
mozilla/experimenter pull request #10889
Opened 2024-06-20 18:23 UTC by brennie

Because:
- the prefFlips feature on Firefox Desktop publishes to a different collection than regular Firefox Desktop experiments

this commit:
- updates the review URL for experiments with this feature.

Fixes #10829.

2024-06-20 19:59 UTC, jaredlockhart requested changes
We gotta add the secure collection to this list here to pickup all the changes correctly:

https://github.com/mozilla/experimenter/blob/main/experimenter/experimenter/kinto/tasks.py#L36-L41

2024-06-20 20:03 UTC, jaredlockhart commented
These are all the flows we have to keep intact with the secure collection:

https://github.com/mozilla/experimenter/tree/main/docs/experimenter#workflows

2024-06-21 13:48 UTC, brennie commented
> We gotta add the secure collection to this list here to pickup all the changes correctly:
> 
> https://github.com/mozilla/experimenter/blob/main/experimenter/experimenter/kinto/tasks.py#L36-L41

Yes, there is a separate bugs filed for that (#10830 and #10831). It isn't as simple as just adding it to that list, so I'm handling it in a separate PR. (Coming soon ™️.)

2024-06-26 14:45 UTC, jaredlockhart approved these changes
Oh yep then this looks good thnx @brennie 🎉

2024-06-26 17:39 UTC, merged