test(cirrus): Cirrus preview flag
mozilla/experimenter pull request #11167
Opened 2024-08-07 16:47 UTC by yashikakhurana

Because

- We added preview flag support for Cirrus to enable them to QA

This commit

- Add a new test to test preview flag functionality

Fixes #11103

2024-08-23 18:56 UTC, jaredlockhart requested changes
Hooray!!  Couple ideas to clean this up a bit 🙏

2024-08-23 18:56 UTC, jaredlockhart commented on experimenter/tests/integration/nimbus/test_cirrus_integration.py
> +    assert displayed_text in ["Control branch", "Treatment branch"]
Pull all these references to `"Control branch"` `"Treatment branch"` out into constants pls 🙏

2024-08-23 18:56 UTC, jaredlockhart commented on experimenter/tests/integration/nimbus/test_cirrus_integration.py
> +    assert result_text_element.is_displayed()
There's a lot of string constants and methods for querying the demo app we should be pulling out into constants on the demo app page object.

2024-08-23 18:56 UTC, jaredlockhart commented on experimenter/tests/integration/nimbus/pages/demo_app/frontend.py
> +    def fill_and_send_form_data(self, client_id, context, nimbus_preview=False):
We have this DemoAppPage class here, can we move all the string constants onto constants here with some convenience methods for interacting with this page so the tests aren't quite so long? 🙏

2024-08-26 15:14 UTC, jaredlockhart approved these changes
Awesome looks great @yashikakhurana 🎉 🎉 🎉 🎉

2024-08-26 16:13 UTC, merged

2024-08-26 16:37 UTC, b4handjr commented
I didn't look at this but we talked at MozWeek, nice job here!