feat(project): docker run with --rm
mozilla/experimenter pull request #11664
Opened 2024-10-31 17:53 UTC by brennie

Because:

- we are creating many short-lived containers for commands; and
- we are not cleaning them up except in `make kill`

This commit:

- updates all docker run commands to use the `--rm` flag so that they are automatically deleted after the container exits.

Fixes #11662

2024-10-31 17:54 UTC, brennie commented
Blocked on #11663

2024-10-31 18:14 UTC, jaredlockhart commented on Makefile
> +		--rm \
If we're doing this pattern of

```
$(COMPOSE) run \
		--rm \
```

everywhere, could we just add it as another alias at the top of the file so we don't have to repeat it everywhere? 🤔

2024-11-01 19:24 UTC, jaredlockhart requested changes

2024-11-01 19:24 UTC, jaredlockhart commented on Makefile
> +COMPOSE_TEST_RUN = ${COMPOSE} run --rm
Should this not be

```
COMPOSE_TEST_RUN = ${COMPOSE_TEST} run --rm
```

?

2024-11-01 19:30 UTC, brennie commented on Makefile
> +COMPOSE_TEST_RUN = ${COMPOSE} run --rm
Yes :)

2024-11-08 20:07 UTC, merged