chore(project): Stop publishing experimenter to dockerhub for deployment
mozilla/experimenter pull request #11666
Opened 2024-10-31 18:23 UTC by brennie

Because:

- we are deploying through GCR images now

This commit:

- removes our push to dockerhub for deployment.

Fixes #11665

2024-10-31 19:01 UTC, mikaeld commented
AFAIK this can be removed as well, GCPv2 uses GAR, not GCR.

```yaml
      - run:
          name: Deploy to Google Container Registry
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud auth configure-docker
            DOCKER_IMAGE="gcr.io/${GOOGLE_PROJECT_ID}/experimenter"
            docker tag experimenter:deploy ${DOCKER_IMAGE}:latest
            docker push "${DOCKER_IMAGE}:latest"
            GIT_SHA=$(git rev-parse --short HEAD)
            docker tag experimenter:deploy ${DOCKERHUB_REPO}:${GIT_SHA}
            docker push ${DOCKERHUB_REPO}:${GIT_SHA}
```

2024-10-31 19:22 UTC, jaredlockhart requested changes

2024-10-31 19:22 UTC, jaredlockhart commented on .circleci/config.yml
> -            make build_prod
We'll need to keep these two lines since the GAR push below starts at tagging but doesn't include the build step

2024-11-01 16:29 UTC, jaredlockhart approved these changes
Okay yep looks good thnx @brennie 🙏

2024-11-01 16:49 UTC, merged