fix #3403 feature(nimbus): support mobile remote settings collection
mozilla/experimenter pull request #3875
Opened 2020-11-02 20:50 UTC by jaredlockhart

Because

* We need to be able to send experiments to the relevant remote settings bucket for desktop and mobile experiments

This commit

* Moves the kinto bucket/collection configuration out of environment and into settings because it's consistent across all deployments
* Adds the mobile collection constant
* Modifies the kinto tasks to push to the relevant collection and monitor all collections for live/complete changes

2020-11-02 22:36 UTC, bbangert commented on app/experimenter/settings.py
> +KINTO_COLLECTION_NIMBUS_MOBILE = "nimbus-mobile-experiments"
👍

2020-11-02 22:37 UTC, bbangert requested changes
Looks good! Needs re-base for migration before merge.

2020-11-02 22:40 UTC, jaredlockhart commented
HA! good idea requesting change to keep the migrations in sync ;)

2020-11-03 17:36 UTC, bbangert approved these changes
Verrrry nice! 👍

2020-11-03 17:37 UTC, merged