[WIP] It's faster.
mozilla/experimenter pull request #5318
Opened 2021-05-28 20:03 UTC by emtwo

2021-05-31 18:40 UTC, jaredlockhart requested changes
Very nice!  This will be such a good change.  Couple ideas on moving some stuff around, adding logging to the task, but generally looks good 👍

2021-05-31 18:40 UTC, jaredlockhart commented on app/experimenter/visualization/api/v3/views.py
> +    return Response(experiment.results_data or {})
If we wanna do this maybe make it the default value on the field?

2021-05-31 23:16 UTC, tdsmith commented
I was looking at the v3 views the other day and realized that we hadn't thought about how splitting the results into multiple files was creating challenges. An architectural alternative to caching here could be to use [signed URLs](https://cloud.google.com/storage/docs/access-control/signing-urls-manually) and [gzip-encoded data](https://cloud.google.com/storage/docs/transcoding) to push small blobs directly to the client from GCS instead of round-tripping them through Django at all.

Will there be a way to trip this by hand? It'd be nice to have less than 24 h of latency, especially if Experimenter deploys and the ETL milk run get out of sync or if we run new results by hand.

2021-06-02 15:58 UTC, jaredlockhart commented
@tdsmith good points.  The other motivating factor here was a recent conversation with @shell1 where she indicated we'll want to be able to sort/filter based on experiment results, so for that we'd need them in the database so I was hoping to kill two birds with one stone here, fetch them into the db for fast lookups and make them available to other future use cases.

2021-06-02 16:01 UTC, emtwo commented
We can also add a check for the timestamp on the data files and if it's sooner than the most recent cache, then pull in the update

2021-06-08 19:00 UTC, jaredlockhart commented
@emtwo if jetstream only runs once a day and we check once a day what's the case where they'll be more up to date?

2021-06-11 15:27 UTC, emtwo commented
> @emtwo if jetstream only runs once a day and we check once a day what's the case where they'll be more up to date?

If we update the cache in the morning, for example, and Jetstream updates the data at noon. Then if someone queries results from experimenter at 4pm the jetstream files will be more recently updated than the cache.

2021-06-14 17:41 UTC, jaredlockhart requested changes
Yeah all looks right but we should add all the metrics and logging to the tasks so we can track them

2021-06-14 21:26 UTC, jaredlockhart approved these changes
Yep, just two `completed` metrics but g2g! Thanks @emtwo !  This is gonna really speed things up 👏 👏 👏 👏 👏

2021-06-14 21:26 UTC, jaredlockhart commented on app/experimenter/jetstream/tasks.py
> +        experiment.save()
`metrics.incr("fetch_experiment_data.completed")` here

2021-06-14 21:26 UTC, jaredlockhart commented on app/experimenter/jetstream/tasks.py
> +            fetch_experiment_data.delay(experiment.id)
`metrics.incr("fetch_jetstream_data.completed")` here

2021-06-16 16:59 UTC, merged