fixes #5803 feat(reporting): Add celery task to generate reportlogs
mozilla/experimenter pull request #5863
Opened 2021-07-05 06:26 UTC by tiftran

This commit:

    * adds a celery task that generates reportlogs from changelongs and normandy history

 Because:
    * This will help aggregate data for stats that will be generated

2021-07-07 19:00 UTC, jaredlockhart approved these changes
Looking great so far @tiftran  this is gonna be so useful 🙏

2021-07-09 14:08 UTC, jaredlockhart requested changes
Oh I don't think I meant to approve.

2021-07-14 18:12 UTC, tiftran commented on app/experimenter/reporting/tasks.py
> +            return ReportLog.EventReason.RELAUNCH
hah, legacy has `experiment.parent`!,

2021-07-14 18:12 UTC, tiftran commented on app/experimenter/reporting/tasks.py
> +            create_reportlog_from_normandy_history(experiment)
I tried it out locally, it didn't seem to have any problems, reportlogs were generated pretty quickly. Could we try the task without a cap? currently it's scheduled to run once a day?

2021-07-14 19:50 UTC, jaredlockhart commented on app/experimenter/reporting/tasks.py
> +            create_reportlog_from_normandy_history(experiment)
Yeah sounds good 👍 Also thanks for doing a test run!

2021-07-14 19:54 UTC, jaredlockhart approved these changes
Alrighty!  Looking good!  There's a convenience method for looking up the application_config on a NimbusExperiment, but other than that looks pretty solid to me.  Great job @tiftran ! 🎉 🎉 🎉 🎉

2021-07-14 19:54 UTC, jaredlockhart commented on app/experimenter/reporting/tasks.py
> +        application_slug = NimbusConstants.APPLICATION_CONFIGS[application].slug
There's already a method for this:

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/models/nimbus.py#L225-L228

2021-07-14 19:54 UTC, jaredlockhart commented on app/experimenter/reporting/tasks.py
> +    return ReportLog.EventReason.NEW
👏 👏 👏 👏 👏 👏 👏

2021-07-14 19:55 UTC, jaredlockhart commented on app/experimenter/settings.py
> +        "schedule": config("CELERY_REPORTING_INTERVAL", default=86400, cast=int),
Oh and you should add this setting to .env.sample

2021-07-15 19:21 UTC, merged