fixes #5865 feat(reporting): Add reportlog frontend
mozilla/experimenter pull request #5897
Opened 2021-07-07 17:57 UTC by tiftran

2021-07-27 18:38 UTC, jaredlockhart reviewed
?

<img width="1100" alt="Screen Shot 2021-07-27 at 2 37 59 PM" src="https://user-images.githubusercontent.com/119884/127209448-28c53b4c-9c6e-4d24-b623-eefbabdcb13d.png">

2021-07-27 18:48 UTC, jaredlockhart commented
Also probably wanna move the built assets path: 

`app/experimenter/assets/`

to something like 

`app/experimenter/reporting-ui/assets/` 

and add it to .gitignore/.dockerignore

2021-07-27 18:49 UTC, jaredlockhart commented
Maybe you could even move `reporting-ui` into `app/experimenter/reporting/`?

2021-08-06 20:14 UTC, jaredlockhart commented
Looking good so far! Couple thoughts

* move the filters into that little subheader
* capitalize your column titles
* Add a 'no results returned' message if it comes back empty

2021-08-09 20:52 UTC, jaredlockhart requested changes
Awesome work tif, looks great and works great.  Couple little cleanupy things but nothing major.  Couple ideas about the UI:

![Screenshot 2021-08-09 at 16-44-29 Mozilla Experimenter](https://user-images.githubusercontent.com/119884/128772667-d31518bf-4be9-46ab-b728-ebaa7903df53.png)
* The `Experiment Reporting` title is super big, maybe look at the other templates to see what header size we use on those?
* Before you had it all in the page body and the subheader was empty, and now you've added both the dates/buttons AND the table itself to the subheader, can you see if you can put the dates/buttons in the subheader but the table in the body?  You might have to move the react root up a block level and then render the subheader and body divs inside your react component.  If it's too much hassle don't worry about it.

2021-08-09 20:52 UTC, jaredlockhart commented on Makefile
> +TYPECHECK_REPORTING = yarn workspace @experimenter/reporting lint:tsc
Probably also wanna add the estlint, tsc, and test commands to `make check`?

2021-08-09 20:52 UTC, jaredlockhart commented on app/experimenter/experiments/views.py
> +    template_name = "experiments/reporting.html"
I think you should move this template into `app/experimenter/reporting/templates`?

2021-08-09 20:52 UTC, jaredlockhart commented on app/experimenter/reporting/reporting-ui/__tests__/App.test.tsx
> +import "@testing-library/jest-dom/extend-expect";
Very nice to have the frontend tests 👍

2021-08-09 20:52 UTC, jaredlockhart commented on app/experimenter/reporting/reporting-ui/components/App.tsx
> +      `${window.location.origin}/api/v7/${startDate}/${endDate}`,
No trailing slash here?? 😱

2021-08-09 20:52 UTC, jaredlockhart commented on docker-compose.yml
> +      - /app/experimenter/reporting/reporting-ui/node_modules/
Make sure to add this to every `app:dev` container below so they all have the same list of volumes

2021-08-10 16:30 UTC, tiftran commented on app/experimenter/experiments/views.py
> +    template_name = "reporting.html"
this is still a little wonky, i tried reporting/reporting.html and reporting-ui/reporting.html and the template paths it made to find the template didn't work out.
did I do something wrong in settings.py?

2021-08-11 15:24 UTC, jaredlockhart commented
I think it's fetching the wrong API path?

<img width="1199" alt="Screen Shot 2021-08-11 at 11 23 52 AM" src="https://user-images.githubusercontent.com/119884/129057365-d92362a8-bee8-47fe-85de-358bc41439ca.png">

2021-08-11 15:36 UTC, jaredlockhart requested changes
Yeah just move everything that's particular to reporting into the `reporting/` app

2021-08-11 15:36 UTC, jaredlockhart commented on app/experimenter/urls.py
> +    ExperimentReportView,
Stick this in `reporting/views.py`

2021-08-11 15:36 UTC, jaredlockhart commented on app/experimenter/settings.py
> +            os.path.join(BASE_DIR, "reporting", "reporting-ui", "templates"),
This looks right to me 👍

2021-08-12 18:27 UTC, jaredlockhart approved these changes
Awesome all looks right to me \o/ 🎉

2021-08-12 18:29 UTC, jaredlockhart commented
Oh and do you wanna add a link to it on the legacy landing page or something?

2021-08-12 18:29 UTC, jaredlockhart commented
Oh and we still have the old export as CSV link.  Are we gonna get rid of that?

2021-08-12 18:35 UTC, merged