fix #6587 feat(nimbus): support multiple feature configs
mozilla/experimenter pull request #6675
Opened 2021-11-15 21:05 UTC by jaredlockhart

Because

* Experiments need to be able to target multiple features
* We'll need to store multiple FeatureConfigs on an experiment
* We'll need to store multiple feature values on each branch

This commit

* Changes the foreign key on NimbusExperiment to a many to many field
* Adds a new model to store a feature value for each feature config on each branch
* Updates the NimbusExperimentFactory to populate the data correctly
* Shims the V5 and V6 APIs to maintain backwards compatibility with the existing interfaces
* Data migrates from the old structure to the new one

2021-11-17 19:29 UTC, lmorchard requested changes
I think I caught a couple of things:

1. The screenshot cloning seems redundant.

1. The integration test failure looks legit. When I create an experiment locally, I get a "field may not be blank" error from GQL for a disabled feature value when I hit "Save and Continue". But, since the feature is disabled, the value field is not revealed to edit or display the validation error. That looks like what the integration test is tripping over

![image](https://user-images.githubusercontent.com/21687/142269411-488e4e8a-156b-4eec-b478-b3bcd344860f.png)

2021-11-17 20:36 UTC, jaredlockhart commented on app/experimenter/experiments/models/nimbus.py
> +            screenshot.save()
Oh you know what this is a bad rebase, I'll take that out.

2021-11-17 20:37 UTC, jaredlockhart commented
Yep I gotta fix that form, good job integration tests!

2021-11-22 22:13 UTC, lmorchard approved these changes
Looks fixed up to me!

2021-11-23 16:23 UTC, merged