fix #6769 feat(nimbus): enable version targeting on mobile
mozilla/experimenter pull request #7131
Opened 2022-03-16 19:22 UTC by jaredlockhart

Because

* Mobile clients now support version targeting

This commit

* Enables version targeting for mobile on supported clients
* Only includes version targeting for mobile clients above the minimum supported version

2022-03-16 21:49 UTC, jrbenny35 approved these changes

2022-03-16 21:49 UTC, jrbenny35 commented on app/experimenter/experiments/models/nimbus.py
> +                    "version|versionCompare('{version}') >= 0".format(
Why are you using ```.format``` vs an f-string?

2022-03-16 22:52 UTC, eliserichards approved these changes
Looks good! This is going to be really useful 📱

2022-03-17 15:35 UTC, tarikeshaq requested changes
Came across this and I think the parameter in mobile is `app_version` (which really it shouldn't be, it's always been like this in the SDK but I think we should make it consistent with desktop)

Starting to think that maybe we should prioritize the SDK targeting integration tests to catch stuff like this 😕

2022-03-17 15:35 UTC, tarikeshaq commented on app/experimenter/experiments/models/nimbus.py
> +                    "version|versionCompare('{version}') >= 0".format(
```suggestion
                    "app_version|versionCompare('{version}') >= 0".format(
```

This is annoying, but I think it should be `app_version` from https://github.com/mozilla/application-services/blob/main/components/nimbus/src/tests/test_evaluator.rs#L109 

it's changeable, I'll file a ticket to create another `version` parameter with the same value, so we can end up depricating the `app_version` for consistency with desktop

2022-03-21 21:35 UTC, jaredlockhart commented on app/experimenter/experiments/models/nimbus.py
> +                    "version|versionCompare('{version}') >= 0".format(
Oh yeah good point 👍

2022-03-21 21:35 UTC, jaredlockhart commented
> Came across this and I think the parameter in mobile is `app_version` (which really it shouldn't be, it's always been like this in the SDK but I think we should make it consistent with desktop)
> 
> Starting to think that maybe we should prioritize the SDK targeting integration tests to catch stuff like this 😕

Yep I've already been talking to @jrbenny35 about exactly this for exactly this reason 👍

2022-03-21 23:23 UTC, eliserichards reviewed
LGTM! I'll leave the final r+ to @tarikeshaq though :)

2022-03-21 23:23 UTC, eliserichards commented on app/experimenter/experiments/models/nimbus.py
> +            version_key = "app_version"
👏

2022-03-22 00:11 UTC, tarikeshaq approved these changes
The versions and targeting parameter look good to me! Do you know if there be any type of QA or A/A experiment since this is the first time we expose this for mobile?

2022-03-22 17:10 UTC, jaredlockhart commented
> The versions and targeting parameter look good to me! Do you know if there be any type of QA or A/A experiment since this is the first time we expose this for mobile?

Filed https://mozilla-hub.atlassian.net/browse/QA-1438

2022-03-22 17:10 UTC, merged