fix #7351 chore(project): add make command for gcloud auth
mozilla/experimenter pull request #7361
Opened 2022-06-02 19:34 UTC by mikewilli

Because

* certain local dev requires authenticating to GCP
* GCP expires authentication periodically

This commit

* adds a helpful `make auth` command to run the required commands

2022-06-02 19:51 UTC, jaredlockhart requested changes
Don't forget to do the thing I literally always forget to do.... update the README!

Also awesome thank you @mikewilli this whole process is so much easier now 🙏

2022-06-02 19:51 UTC, jaredlockhart commented on Makefile
> +auth:
I might name this something more explicitly clear that it's for gcloud like `gcloud_auth` or something?

2022-06-02 20:00 UTC, mikewilli commented on README.md
> +    - `make auth`
:facepalm: ...fixed

2022-06-03 17:30 UTC, jaredlockhart approved these changes
Looks good to me and works locally, I'd like someone else to try it too @yashika-khurana @eliserichards ?

2022-06-03 17:58 UTC, yashika-khurana commented
> Looks good to me and works locally, I'd like someone else to try it too @yashika-khurana @eliserichards ?

I am testing it now 😊

2022-06-03 18:30 UTC, yashika-khurana commented
Worked for me. thanks @mikewilli 😊

2022-06-03 18:31 UTC, yashika-khurana approved these changes

2022-06-03 18:35 UTC, merged