fixes #7592 type(test): Added end-to-end test for telemetry verification during enrollment and unenrollment
mozilla/experimenter pull request #7634
Opened 2022-08-23 18:20 UTC by jrbenny35

Because
* Making sure telemetry is sent when a client enrolls and unenrolls is very important. We did not have automated tests for this though

This Commit
* Adds automated checks for telemetry enroll/unenroll events.

Since this test can take a varying amount of time to complete, I utilized pytest-xdist to group tests so that this test can be run immediately, to save time.
I also had to write a ping server to collect and verify the pings, that is included in this PR.

2022-08-23 19:02 UTC, yashika-khurana commented
@jrbenny35 oh I see one check is failing :(

2022-08-23 19:03 UTC, jrbenny35 commented
> @jrbenny35 oh I see one check is failing :(

Yeah, seems another test is failing. Not sure why exactly

2022-08-23 19:10 UTC, yashika-khurana commented
@jrbenny35 it seems like error in screenshot test case and not able to find particular file

2022-08-23 21:15 UTC, jrbenny35 commented
> @jrbenny35 it seems like error in screenshot test case and not able to find particular file

Yup, it was a pref I had set. I moved all the prefs regarding the telemetry tests into the file with the test

2022-08-23 21:15 UTC, jrbenny35 commented
Just making sure everything works on release now

2022-08-24 14:34 UTC, yashika-khurana requested changes
LGTM!, just minor comment, great job @jrbenny35 👏 👏 🎉

2022-08-24 14:34 UTC, yashika-khurana commented on app/tests/integration/nimbus/conftest.py
> +        print(response.text)
oops print statement!

2022-08-24 14:34 UTC, yashika-khurana commented on app/tests/integration/nimbus/conftest.py
> +        print(response.text)
same here!

2022-08-25 14:13 UTC, yashika-khurana commented
@jrbenny35 it looks good to me, I am just wondering if we can write a test case where enrollment shouldn't happen? so that we can make sure enrollment doesn't happen in those cases where it shouldn't. Just a thought 🤔

2022-08-25 14:15 UTC, jrbenny35 commented
> @jrbenny35 it looks good to me, I am just wondering if we can write a test case where enrollment shouldn't happen? so that we can make sure enrollment doesn't happen in those cases where it shouldn't. Just a thought 🤔

Yeah, that wouldn't be hard. Just check for the ```enrollFailed``` event and the reason being a JEXL mismatch or something. I can file that on JIRA

2022-08-25 14:19 UTC, yashika-khurana commented
@jrbenny35 perfect, lets merge this and we can add that next. Thanks @jrbenny35 its awesome, great job 🚀

2022-08-25 14:20 UTC, yashika-khurana approved these changes

2022-08-25 14:30 UTC, merged