fix #7628 fix(nimbus): Hide add branch button when creating a rollout
mozilla/experimenter pull request #7638
Opened 2022-08-24 21:14 UTC by eliserichards

Because...

* The "+ Add branch" button on the Branches page is still showing when we set the experiment to be a rollout
* `handleAddBranch` was still adding branches in the backend (if you unselect isRollout you see the hidden branches)

This commit...

* Checks the state of `isRollout` before adding a branch
* The "+ Add branch" button disappears as soon as rollout is clicked

#7628

2022-08-24 21:25 UTC, jrbenny35 approved these changes

2022-08-25 14:18 UTC, yashika-khurana requested changes
Changes look good to me 👏 👏 🎉 🎉 , I think its worth adding test for that 😆

2022-08-25 14:18 UTC, jrbenny35 requested changes
Actually, could we add a check to this e2e test to make sure that the "Add Branch" button is not displayed after promoting to rollout?

https://github.com/mozilla/experimenter/blob/15ac46679007545e8cfcca21748920e10f4d5272/app/tests/integration/nimbus/test_experimenter.py#L49-#L56

2022-08-25 18:50 UTC, eliserichards commented
There's already a test for `{!isRollout && ( <Button ...` --  https://github.com/mozilla/experimenter/blob/800fb0561f0544c59944c7ef869ec8b8bae15f76/app/experimenter/nimbus-ui/src/components/PageEditBranches/FormBranches/index.test.tsx#L33

I'm not sure about adding this to the e2e tests, since the UI is going to be changing for this in the future 🤔 Let's merge this for now and file a ticket to add additional tests

2022-08-25 19:43 UTC, yashika-khurana commented
@eliserichards my bad, thank you for verifying its already there, looks great 🚀 👏 👏

2022-08-25 19:44 UTC, yashika-khurana approved these changes
lets roll this out 🚀

2022-08-25 22:09 UTC, merged