fix #7661 chore(nimbus): Update integration_sdk_shell command
mozilla/experimenter pull request #7662
Opened 2022-09-01 16:48 UTC by yashika-khurana

Because

* When we try to run `make integration_sdk_shell` locally, it will give us this error
`Pulling app (app:deploy)... ERROR: pull access denied for app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied make: *** [integration_sdk_shell] Error 1`

We need to build prod while running those test cases

This commit

* Update make command and config to include `build_prod` command

2022-09-01 16:52 UTC, jrbenny35 requested changes
I see changes in ```.circleci/``` in here, did you mean to include those?

2022-09-01 18:48 UTC, jaredlockhart requested changes

2022-09-01 18:48 UTC, jaredlockhart commented on Makefile
>  integration_shell:
Sorry I meant to add it to all of the integration commands

2022-09-01 18:49 UTC, jaredlockhart commented
> I see changes in `.circleci/` in here, did you mean to include those?

Yeah adding the `build_prod` as a dependency to those make commands means if they're run individually as they were before it'll rebuild the containers in between `make up_prod_detached` and `make integration_test_legacy` whereas if you fold them together into a single command make will run `build_prod` once at the start.

2022-09-01 20:21 UTC, jaredlockhart commented on Makefile
>  integration_vnc_up_detached:
What about these two?

2022-09-02 15:42 UTC, jaredlockhart approved these changes
Tytytyty 🙏

2022-09-02 16:14 UTC, merged