Fixes #7629 fix(nimbus): Remove treatment branches when setting is_rollout on branches page
mozilla/experimenter pull request #7718
Opened 2022-09-08 22:24 UTC by eliserichards

Because...

* Not changing the treatment branch state in the db when `is_rollout=True` on the Branches page

This commit...

* Updates the is_rollout action to remove treatment branches when `is_rollout=True`

#7629

2022-09-09 16:03 UTC, jaredlockhart submitted a review, later dismissed
Yep great pattern here, make the API check and reject for the case, and do the emptying in the frontend, just need a frontend test I think?

2022-09-09 16:03 UTC, jaredlockhart commented on app/experimenter/experiments/tests/api/v5/test_serializers/test_nimbus_ready_for_review_serializer.py
> +        self.assertEqual(error[0:14], "A rollout may ")
The API is sending back a constant error message, `NimbusConstants.ERROR_SINGLE_BRANCH_FOR_ROLLOUT`, so can't you just compare to that?

2022-09-09 16:03 UTC, jaredlockhart commented on app/experimenter/nimbus-ui/src/components/PageEditBranches/FormBranches/reducer/actions.ts
> +    treatmentBranches,
Yeah exactly, but we also need tests in the frontend for this 🙏

2022-09-09 23:00 UTC, yashika-khurana requested changes
great job @eliserichards having a backend check and frontend not sending treatment branches at all `[]` is amazing ❤️, Also I am concerned about how we gonna clean up the database which already consists of `treatment_branches`, are we gonna manually clean that or we gonna write migration?? 🤔

2022-09-13 17:02 UTC, jaredlockhart approved these changes
Tested locally, all works perfectly, code looks all right to me, tests are very succinct, excellent work A+ 10/10 cats 😸

2022-09-13 17:02 UTC, jaredlockhart commented on app/experimenter/experiments/tests/api/v5/test_serializers/test_nimbus_ready_for_review_serializer.py
> +            [NimbusConstants.ERROR_SINGLE_BRANCH_FOR_ROLLOUT],
👏 👏 👏 👏 👏

2022-09-13 17:02 UTC, jaredlockhart commented on app/experimenter/nimbus-ui/src/components/PageEditBranches/FormBranches/index.test.tsx
> +    );
👌 👌 👌 👌 👌 👌

2022-09-13 19:31 UTC, yashika-khurana commented
> great job @eliserichards having a backend check and frontend not sending treatment branches at all `[]` is amazing ❤️, Also I am concerned about how we gonna clean up the database which already consists of `treatment_branches`, are we gonna manually clean that or we gonna write migration?? 🤔

@jaredlockhart What do you think is the best way to cleanup things? 💭

2022-09-13 20:06 UTC, jaredlockhart commented
> 

Oh this'll happen automatically for anything still in Draft, and I don't think anything's launched with it yet so we should be okay.

2022-09-13 20:33 UTC, yashika-khurana commented
@jaredlockhart thank you for confirming, sounds good to me 🚀

2022-09-13 20:34 UTC, yashika-khurana approved these changes
lets roll it out 🚀 , great job @eliserichards 👏

2022-09-14 15:45 UTC, merged

2022-09-14 15:50 UTC, yashika-khurana commented
@eliserichards so sorry about that, I think you need to revert snake case