fix #7762 chore(nimbus): Add python script to aide in targeting expression testing (mobile)
mozilla/experimenter pull request #7763
Opened 2022-09-20 21:57 UTC by jrbenny35

Because
* Testing targeting expressions can sometimes be quite cumbersome to do locally

This commit
* Adds a script to allow a user to input a custom context and targeting expression and see how they evaluate.

2022-09-21 17:16 UTC, yashika-khurana requested changes
Let me message you on slack, I am trying to do these step

2022-09-21 17:16 UTC, yashika-khurana commented on Makefile
> +	PYTHONPATH=/application-services/components/nimbus/src $(COMPOSE_INTEGRATION) run rust-sdk bash
I think we should store the path in some variable and then use it here

2022-09-22 17:26 UTC, yashika-khurana commented on README.md
> +python sdk_eval_check.py --targeting "(app_version|versionCompare('106.*') <= 0) && (is_already_enrolled)"
shouldn't be this `--targeting-string .........`

2022-09-22 21:18 UTC, jaredlockhart approved these changes
Wow.  Wow wow wow.  Wow.  This is VERY cool.  Just tested locally, works perfectly, documentation worked perfectly and is clear.  Very very cool.  I love it.  Ticket is written clearly, marked up correctly, code is very clear, documentation is clear.  This is super duper handy, 11/10 A++ 👏 👏 👏 👏 👏 

![wow](https://user-images.githubusercontent.com/119884/191852858-cdece2be-6b12-42c6-912e-c8358bca77e4.gif)

2022-09-22 22:34 UTC, yashika-khurana approved these changes
Awesome looks perfect, all instructions are very clear. thanks, @jrbenny35 👏

2022-09-23 04:03 UTC, jrbenny35 commented
Thank you both!

2022-09-23 04:19 UTC, merged