fixes #7889 feat(nimbus): Change circleci test jobs to be more descriptive
mozilla/experimenter pull request #7890
Opened 2022-10-31 16:58 UTC by jrbenny35

Because:
* Currently we run a lot of parallel jobs on circleci and it can be a bit hard to sort through which job does what tests

This Commit:
* Changes the workflow on circleci to be more descriptive so it is easier to see which tests are passing or failing

2022-10-31 20:22 UTC, jrbenny35 commented on .circleci/config.yml
> +            docker save -o saved_images/db_image experimenter_db_1
I don't _have_ to but I wanted to see if I can save time by doing some steps in 1 job instead of repeating

2022-10-31 20:37 UTC, jaredlockhart commented on .circleci/config.yml
> +            docker save -o saved_images/db_image experimenter_db_1
Oh yeah but you don't have to do this at all, the `docker_layer_caching` option above already does this.  It's just expensive, but nobody's mentioned it yet so it's fine.

2022-10-31 20:38 UTC, jaredlockhart commented on .circleci/config.yml
> +            docker save -o saved_images/db_image experimenter_db_1
I wouldn't worry about it, just reorganize them and leave all the building/caching as it is.  If it blows up after we reorganize things we can deal with it later.

2022-11-01 16:14 UTC, jaredlockhart requested changes
First of all, FANTASTIC.  That looks SOOOOOOO MUCH NICER 🙏 🙏 🙏 

One thing I wanted to see is also which ones are testing

- Nimbus UI (like the ones that are testing archiving and cloning etc)
- Remote Settings (all the ones that are testing like launches and timeouts and etc)
- Targeting (the ones that test the jexl expressions in desktop and the sdk)

Could you rename the ones that touch each of those with those labels included?

But also 100% yes to saying like, which app, which channel, etc 👏 👏 👏 👏

2022-11-01 16:18 UTC, jrbenny35 commented
> First of all, FANTASTIC. That looks SOOOOOOO MUCH NICER 🙏 🙏 🙏
> 
> One thing I wanted to see is also which ones are testing
> 
>     * Nimbus UI (like the ones that are testing archiving and cloning etc)
> 
>     * Remote Settings (all the ones that are testing like launches and timeouts and etc)
> 
>     * Targeting (the ones that test the jexl expressions in desktop and the sdk)
> 
> 
> Could you rename the ones that touch each of those with those labels included?
> 
> But also 100% yes to saying like, which app, which channel, etc 👏 👏 👏 👏

You mean something like this?
```
name: Integration Test Desktop Nimbus UI (Release Firefox)
```

2022-11-01 16:25 UTC, jaredlockhart commented
> > First of all, FANTASTIC. That looks SOOOOOOO MUCH NICER 🙏 🙏 🙏
> > One thing I wanted to see is also which ones are testing
> > ```
> > * Nimbus UI (like the ones that are testing archiving and cloning etc)
> > 
> > * Remote Settings (all the ones that are testing like launches and timeouts and etc)
> > 
> > * Targeting (the ones that test the jexl expressions in desktop and the sdk)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you rename the ones that touch each of those with those labels included?
> > But also 100% yes to saying like, which app, which channel, etc 👏 👏 👏 👏
> 
> You mean something like this?
> 
> ```
> name: Integration Test Desktop Nimbus UI (Release Firefox)
> ```

💯 💯 💯 💯 💯 💯 💯

2022-11-01 16:26 UTC, jaredlockhart commented
I'm not sure if the existing decorators are split up that way, I think some of the Nimbus UI and Remote Settings ones are lumped into the same test run, if it's not too much of a hassle could we split those out?

2022-11-01 16:27 UTC, jaredlockhart commented
Oh yeah like these here:

```
nimbus/test_remote_settings.py::test_create_new_experiment_approve_remote_settings[IOS] PASSED [ 50%]
nimbus/test_remote_settings.py::test_create_new_experiment_approve_remote_settings[FOCUS_IOS] PASSED [100%]
```

I would label as they're testing remote settings, not IOS

2022-11-01 16:28 UTC, jrbenny35 commented
> I'm not sure if the existing decorators are split up that way, I think some of the Nimbus UI and Remote Settings ones are lumped into the same test run, if it's not too much of a hassle could we split those out?

Yeah we have some under ```test_experimenter.py``` that also need to use remote settings. So ALL remote settings tests should have a marker, and anything not using remote settings should just be marked as UI.

2022-11-01 16:29 UTC, jaredlockhart commented
> > I'm not sure if the existing decorators are split up that way, I think some of the Nimbus UI and Remote Settings ones are lumped into the same test run, if it's not too much of a hassle could we split those out?
> 
> Yeah we have some under `test_experimenter.py` that also need to use remote settings. So ALL remote settings tests should have a marker, and anything not using remote settings should just be marked as UI.

YES I think that's exactly the right way to think about it.

Nimbus UI: Things that only test stuff inside experimenter
Remote Settings: Things that involve remote settings in any way
Desktop Targeting: Things that are evaluating JEXL expressions inside desktop
SDK Targeting: Things that are evaluating JEXL expressions inside the SDK

2022-11-01 16:49 UTC, jrbenny35 commented
how does this look
```
markers =
    use_variables: marks tests that need to use pytest-variables
    run_targeting: run jexl targeting tests in firefox
    remote_settings: tests that involve remote settings
    nimbus_ui: tests that only involve the UI, nothing else
    nimbus_integration: tests that integrate with nimbus and external services
```

2022-11-01 19:01 UTC, jrbenny35 commented
I already have an enhancement for this but I want to get this landed first.

2022-11-01 19:27 UTC, jrbenny35 commented
Should I reduce some of the sizing? I don't think we need xlarge anymore

2022-11-01 20:19 UTC, jrbenny35 commented
Reducing some sizing resulted in no losses!

2022-11-02 16:01 UTC, jaredlockhart commented
Fantastic.  Just a couple things:

- Add 'Enrollment' to this:
  - ci/circleci: Integration Test Desktop (Nightly Firefox)
- Add 'Desktop' to these:
  - ci/circleci: Test Targeting (Beta Firefox) — Your tests passed on CircleCI!
  - ci/circleci: Test Targeting (Nightly Firefox) — Your tests passed on CircleCI!
  - ci/circleci: Test Targeting (Release Firefox) — Your tests passed on CircleCI!


But generally yes this is EXACTLY what I wanted, I think this makes it so much easier to navigate.  Thank you @jrbenny35 !

2022-11-02 16:12 UTC, jrbenny35 commented
I think you'll need to disable some checks to get this to land @jaredlockhart

2022-11-02 17:03 UTC, jrbenny35 commented
I fixed the IOS job thing

2022-11-02 21:52 UTC, jaredlockhart commented
How come some say 'Integration....' and some don't?  Maybe 'Integration' is redundant here and can be removed?

2022-11-02 21:53 UTC, jrbenny35 commented
> How come some say 'Integration....' and some don't? Maybe 'Integration' is redundant here and can be removed?

I thought of this too. I removed some but yeah having them all say "Integration" seems a bit much

2022-11-03 05:49 UTC, yashika-khurana commented
@jrbenny35 do you know why some of the circle ci are waiting to get run???

2022-11-03 14:17 UTC, jrbenny35 commented
> @jrbenny35 do you know why some of the circle ci are waiting to get run???

It's because I changed the job names, and github takes a while to update them

2022-11-03 16:15 UTC, jrbenny35 commented on .circleci/config.yml
> +    resource_class: large
yeah and they didn't even run any slower.

2022-11-03 16:18 UTC, merged