For #8107 feat(nimbus): add advanced targeting options for mobile behavioral targeting
mozilla/experimenter pull request #8108
Opened 2023-01-03 21:02 UTC by jeddai

Because...

    The behavioral event store now exists within Firefox iOS and Android

This commit...

    Adds advanced targeting options that leverage the events being recorded.

**A note:** We need two distinct targeting configs for each behavior, one for iOS and one for Android. These are required because the same event is named differently across the two apps. Something I noticed is Experimenter seems to be using the targeting config `slug` field split+capitalized for displaying the config, and I don't think we'd want "Android" and "Ios" showing up in the list. If we do, something worth noting is that "Ios" should be "iOS".

iOS set as the app
<img width="833" alt="image" src="https://user-images.githubusercontent.com/4909307/210440025-b098f24c-9dbd-40e1-bf27-f817a32a2be8.png">

Android set as the app
<img width="846" alt="image" src="https://user-images.githubusercontent.com/4909307/210440084-200ce92d-0ed4-42cf-a118-bf07056d8c13.png">

2023-01-03 21:59 UTC, yashika-khurana requested changes
Meanwhile , just a nit pick

2023-01-03 21:59 UTC, yashika-khurana commented on app/experimenter/targeting/constants.py
> +CORE_ACTIVE_USERS_TARGETING = "'{event}'|eventsCountNonZero('Days', 28, 0) >= 21"
nitpick: Can you move these constants to the top 🆙

2023-01-03 21:59 UTC, yashika-khurana commented on app/experimenter/targeting/constants.py
> +RECENTLY_LOGGED_IN_USERS_TARGETING = "'{event}'|eventsCountNonZero('Weeks', 12, 0) >= 1"
same as before to move this 🆙

2023-01-04 22:33 UTC, jrbenny35 approved these changes

2023-01-04 22:33 UTC, jrbenny35 commented on app/tests/integration/nimbus/conftest.py
> +    return f"{request.node.name[:75]}{str(uuid.uuid4())[:4]}"
1 char too much

2023-01-05 05:32 UTC, yashika-khurana approved these changes

2023-01-05 05:32 UTC, yashika-khurana commented on app/tests/integration/nimbus/conftest.py
> +    return f"{request.node.name[:75]}{str(uuid.uuid4())[:4]}"
😆

2023-01-05 15:19 UTC, merged