For #7823 feat(nimbus): Add population percent and dirty to constants
mozilla/experimenter pull request #8250
Opened 2023-02-03 20:09 UTC by eliserichards

Because...

* We want to allow updates to dirty states and allow editing for population percent for live rollouts

This commit...

* updates the serializer constants to reflect that

2023-02-03 20:15 UTC, yashikakhurana requested changes
I think worth adding little test

2023-02-03 22:00 UTC, eliserichards commented
These are used in the serializers and already have tests :) Also #8239 will add tests once the fields are enabled in the UI

2023-02-06 14:59 UTC, jaredlockhart commented on app/experimenter/experiments/api/v5/serializers.py
> +            NimbusExperiment.PublishStatus.DIRTY,
Shouldn't this be under rollouts?

2023-02-06 18:48 UTC, eliserichards commented on app/experimenter/experiments/api/v5/serializers.py
> +            NimbusExperiment.PublishStatus.DIRTY,
🤦‍♀️

2023-02-07 18:45 UTC, yashikakhurana approved these changes
looks good, thank you for pointing to the right test cases 👏

2023-02-07 19:31 UTC, merged