Fixed Issue #7900
mozilla/experimenter pull request #8603
Opened 2023-03-29 01:32 UTC by AnshBhardwaj1

Issue  #7900 was to create uniformity throughout the code, by using single quotes for strings.

The issue was in [Channel Targetting](https://github.com/mozilla/experimenter/blob/842cb5143c2f82cfebcd0f9d72faf79e7a990990/app/experimenter/experiments/models.py#L328) meanwhile the other [opt-out pref check](https://github.com/mozilla/experimenter/blob/842cb5143c2f82cfebcd0f9d72faf79e7a990990/app/experimenter/experiments/models.py#L331l) had no problem and all the strings were in single quotes.
The tests_models.py file which had to be updated was missing, so I could not work on that.

2023-03-29 15:42 UTC, yashikakhurana requested changes
@AnshBhardwaj1 thank you for working on this, but your tests are failing, can you please also update them, thanks

2023-03-30 01:31 UTC, AnshBhardwaj1 commented
I will be shortly fixing the tests. 
Thank you

2023-03-30 10:20 UTC, AnshBhardwaj1 commented
@yashikakhurana can you please tell me, why are tests failing? Actually, this is my first-ever pull request, and after working on it for multiple hours. I am not able to figure out why the tests are failing. 

Thank you

2023-03-30 16:30 UTC, yashikakhurana commented
@AnshBhardwaj1 by running make check command I can see that dictionary of the results are not equal in test cases, earlier the value was in `" "`, now they are in `' '`, you need to modify that

2023-03-31 01:51 UTC, closed without merging