fixes #8210 feat(nimbus):Added link to metric hub documentation for r…
mozilla/experimenter pull request #8608
Opened 2023-03-29 22:14 UTC by Avi-88

…espective outcomes

Because

- there are now nice auto generated docs for each outcome in metric hub

This commit

- adds links to each outcome, mapping it to its respective documentation in metric hub

[Video demo of the changes made](https://drive.google.com/file/d/1HLsLRKr1CsenhZ-scp13lzUVVTYAE8bV/view)

2023-03-29 22:15 UTC, Avi-88 commented
Hello @yashika-khurana ma'am, please review the code and let me know if any further changes are required, thanks

2023-03-30 16:24 UTC, yashikakhurana requested changes
nothing major, thank you @Avi-88 if you will notice before the outcomes were separated with `,` now they are separated with `|`, I would suggest to keep `,` :)

2023-03-30 19:45 UTC, Avi-88 commented
Updated it to use `,` instead of `|`.

![image](https://user-images.githubusercontent.com/79744258/228947414-8384cbff-7d35-43b3-b105-c65da6ae2d77.png)

2023-03-31 05:00 UTC, yashikakhurana commented on experimenter/experimenter/nimbus-ui/src/components/Summary/TableOverview/index.tsx
> +          {acc} , {curr}
you can remove extra space here like `          {acc}, {curr}`

2023-03-31 05:01 UTC, yashikakhurana requested changes
one minor minor formatting to look better

2023-03-31 14:09 UTC, Avi-88 commented
> one minor minor formatting to look better

Hello @yashikakhurana  ma'am, I have made the requested changes please let me know if anymore changes are required, thanks

2023-03-31 16:04 UTC, yashikakhurana commented
@Avi-88 no worries, the fail is not related to your code, I re-ran the test on ci it should be good

2023-03-31 16:06 UTC, yashikakhurana approved these changes
@Avi-88 thank you, and changes are accurate and test cases are on point :)

2023-03-31 16:06 UTC, yashikakhurana commented on experimenter/experimenter/nimbus-ui/src/components/Summary/TableOverview/index.tsx
> +          {outcome?.friendlyName}
great job on describing href 🎉

2023-03-31 16:20 UTC, merged