#8604  docs(nimbus): Update documentation to include how to update fork with main
mozilla/experimenter pull request #8618
Opened 2023-03-30 19:45 UTC by Philipotieno

Because

- We have not specified how to updat the fork with changes on the main branch

This commit

- Updates the read me with how to add an upstream remote
- Updates the read me to include how to update the fork/working-branch with the latest changes on the main repository.

2023-03-30 21:51 UTC, jrbenny35 commented
Hey @Philipotieno 👋🏾 , thanks for the PR!

I think I understand what you are saying but following the steps, your changes wouldn't have much of an effect. When you clone the repo, you are already getting the latest changes, so you don't need to fetch them again.

What were your thoughts when you were creating this PR?

2023-03-31 01:00 UTC, Philipotieno commented
Hello @jrbenny35 I realized that whenever I cloned my forked  repo, I was missing the changes that have been merged on the main repo, so I had to fetch the changes from the main and merge them to my fork, I might have missed something. but for now I have to fetch changes every time for an existing fork, that's why I raised the PR.

2023-03-31 05:10 UTC, yashikakhurana requested changes
Thank you @Philipotieno I think the best place to add this is [contributing.md](https://github.com/mozilla/experimenter/blob/main/contributing.md)

2023-03-31 19:20 UTC, Philipotieno commented
Hi @yashikakhurana, I've updated the `contributing.md`

2023-04-01 00:27 UTC, yashikakhurana requested changes

2023-04-01 00:27 UTC, yashikakhurana commented on contributing.md
> +
you can probably remove 1. above from the three places, give it actual numbering like 1,2,3 or may be bullets like `-`

2023-04-04 02:00 UTC, yashikakhurana approved these changes
thank you @Philipotieno

2023-04-04 02:15 UTC, merged