fixes (#8254) Filters have no effect when applied before the experiment loads
mozilla/experimenter pull request #8631
Opened 2023-04-01 16:59 UTC by cherish2003

### Because
-  Filters have no effect when applied before the experiment loads
### This commit
- Disabled the filters untill the all the experiments loads which resloves this issue 
- Fixes #8254 
### Screenshots
![Screenshot from 2023-04-01 22-00-35](https://user-images.githubusercontent.com/88829894/229304289-0c294265-a535-4e54-9bd9-b02e0a472b7d.png)
- As you can see the filters are disabled untill the experiments loads and gets enabled after loaded

2023-04-01 17:47 UTC, cherish2003 commented
@yashikakhurana kindly review the code let me know any changes are required .Thank you

2023-04-03 17:18 UTC, yashikakhurana requested changes
tested it, working 💯 , just if you can remove the log statement, thank you @cherish2003 🎉

2023-04-03 17:18 UTC, yashikakhurana commented on experimenter/experimenter/nimbus-ui/src/components/PageHome/FilterBar/index.tsx
> +  console.log(loading);
Can you please remove this log?

2023-04-03 17:29 UTC, cherish2003 commented on experimenter/experimenter/nimbus-ui/src/components/PageHome/FilterBar/index.tsx
> +  console.log(loading);
@yashikakhurana i have removed it

2023-04-03 17:33 UTC, yashikakhurana approved these changes
thank you @cherish2003 👏

2023-04-03 18:48 UTC, merged