For #8558 refactor(nimbus): Use isRolloutDirty flag instead of dirty publishStatus
mozilla/experimenter pull request #8715
Opened 2023-04-19 17:05 UTC by eliserichards

Because

- Using the dirty publish status to denote a dirty (edited live) rollout did not allow us to tell if a rollout was dirty when the publish status moved into Review/Approved/Waiting (this happens for request live update and ending the rollout)

This commit

- Changes everything over to use isRolloutDirty instead of publishStatus=Dirty
   - constants
   - v5 serializer
   - models: `can_edit` and `Filters`
   - kinto tasks
   - PageHome rendering the "Unpublished Updates" column (`DirectoryColumnUnpublishedUpdates`)
   - PageSummary and Summary components (approve/reject workflow setting publishStatus)
   - `getStatus`

Related: 
* https://github.com/mozilla/experimenter/pull/8560
* https://github.com/mozilla/experimenter/pull/8671
* https://github.com/mozilla/experimenter/pull/8669

2023-04-20 16:20 UTC, jaredlockhart commented
Let's block this on https://github.com/mozilla/experimenter/pull/8669

2023-04-25 22:35 UTC, eliserichards commented
#8669 is approved, so this is ready for review

2023-04-26 21:29 UTC, jaredlockhart requested changes
Generally looking great 🎉 

Couple nits but also one thing I noticed, there's no reason for `isRolloutDirty` to be `null | false | true` we can just have it be `false | true` so let's update the field to be default false in the db, amend the migration, then we don't need to check for the `null` case at all.

2023-04-26 21:29 UTC, jaredlockhart commented on experimenter/experimenter/experiments/models.py
> +            experiment_data__is_rollout_dirty=True,
God I love that we can define these filters here like this.

2023-04-26 21:29 UTC, jaredlockhart commented on experimenter/experimenter/nimbus-ui/src/components/PageHome/DirectoryTable/index.tsx
> +          {d === true ? "YES" : ""}
You can just get rid of `=== true` altogether.

2023-04-26 21:29 UTC, jaredlockhart commented on experimenter/experimenter/nimbus-ui/src/components/PageHome/DirectoryTable/index.tsx
> +  isRolloutDirty: d,
Why are these single letter variables at all?

2023-04-26 21:29 UTC, jaredlockhart commented on experimenter/experimenter/nimbus-ui/src/components/PageHome/DirectoryTable/index.tsx
> +          {d === true ? "YES" : ""}
Also we're checking `d` above so it will always be `true` by the time we get down here?

2023-04-26 21:29 UTC, jaredlockhart commented on experimenter/experimenter/nimbus-ui/src/components/Summary/index.tsx
> -          : NimbusExperimentPublishStatusEnum.IDLE,
God it's nice to get rid of this 🙏

2023-04-26 21:29 UTC, jaredlockhart commented on experimenter/experimenter/nimbus-ui/src/lib/experiment.ts
> +) => (experiment.isRolloutDirty === true ? "1" : "0");
`=== true` is redundant

2023-05-11 15:54 UTC, jaredlockhart approved these changes
Awesome.  Tested locally, everything seems ship shape.  Code all looks correct.  This is great thank you @eliserichards 🎉 🎉 🎉 

Also let's make sure the state diagram is up to date as well.  Can do that in a followup if it needs it.

2023-05-12 17:54 UTC, merged