8532 analysis index out of range
mozilla/experimenter pull request #8966
Opened 2023-06-13 21:41 UTC by mikewilli

Because

- an error ingesting one metric's results prevents other results from being available

This commit

- checks for an intermittent issue in the data to preempt the error

2023-06-14 16:36 UTC, jaredlockhart requested changes
Can we add a test for this case?

2023-06-14 16:39 UTC, mikewilli commented
Yea I realized it was failing coverage so moved it back to draft.

2023-06-16 00:49 UTC, brennie commented on experimenter/experimenter/jetstream/models.py
> +                ):
`bool(None)` and `bool([])` both eval to `False`, so you can do `if not absolute_primary_metric_vals.all`

2023-06-16 22:18 UTC, yashikakhurana commented on experimenter/experimenter/jetstream/models.py
> +
I am not sure by having this if and continue, how the below 2 statements will affect counts? may be I don't have enough context, just trying to understand 🤔

2023-06-16 22:18 UTC, yashikakhurana reviewed
Just a general question

2023-06-20 13:31 UTC, merged