fixes mozilla#9088 feat(nimbus): add targeting to support existing us…
mozilla/experimenter pull request #9089
Opened 2023-07-10 16:20 UTC by halemu

Land advanced targeting for existing users with no vpn/enterprise history, and haven't disabled recommended features/extensions

2023-07-10 17:03 UTC, brennie requested changes

2023-07-10 17:03 UTC, brennie commented on experimenter/experimenter/targeting/constants.py
> +    " 'Recommend extensions/features'",
Could you reformat these strings like you have in targeting:

```
name=(
    "...."
    "...."
)
```

2023-07-10 17:03 UTC, brennie commented on experimenter/experimenter/targeting/constants.py
> +    " disabled 'Recommend extensions/features'",
Here too.

2023-07-10 17:04 UTC, aminomancer approved these changes
Some formatting nits but looks good

2023-07-10 17:04 UTC, aminomancer commented on experimenter/experimenter/targeting/constants.py
> +    " 'Recommend extensions/features'",
```suggestion
    name=(
        "Existing users, no enterprise or past VPN use, hasn't disabled "
        "'Recommend extensions/features'"
    ),
```

2023-07-10 17:04 UTC, aminomancer commented on experimenter/experimenter/targeting/constants.py
> +    " disabled 'Recommend extensions/features'",
```suggestion
    description=(
        "Exclude users who have used Mozilla VPN, are enterprise users, or have"
        " disabled 'Recommend extensions/features'"
    ),
```

2023-07-10 17:04 UTC, aminomancer commented on experimenter/experimenter/targeting/constants.py
> +    ),
```suggestion
    targeting=(
        f"{EXISTING_USER_NO_ENTERPRISE_OR_PAST_VPN.targeting} && "
        "'browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features'|preferenceValue &&"
        "'browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons'|preferenceValue"
    ),
```

2023-07-10 19:36 UTC, brennie approved these changes

2023-07-11 16:14 UTC, yashikakhurana approved these changes
thank you @halemu 🎉

2023-07-11 16:38 UTC, merged