fix #9107 chore(cirrus): Push to dockerhub
mozilla/experimenter pull request #9108
Opened 2023-07-11 22:04 UTC by yashikakhurana

Because

- Reason

This commit

- Change

2023-07-11 22:14 UTC, yashikakhurana commented on .circleci/config.yml
> +            docker tag cirrus:dev ${DOCKERHUB_CIRRUS_REPO}:cirrus_build
@jaredlockhart we will be requiring a repo for cirrus to tag the latest, who can we reach out to do that?

2023-07-12 14:53 UTC, jeddai commented
@yashikakhurana it looks like we use `mozilla/experimenter` as the repo https://hub.docker.com/r/mozilla/experimenter

Also if you log into CircleCI it looks like we have the ability to add environment variables. https://app.circleci.com/settings/project/github/mozilla/experimenter/environment-variables

2023-07-12 17:36 UTC, yashikakhurana commented
blocking this PR- https://github.com/mozilla/experimenter/issues/9112

2023-07-12 19:01 UTC, jaredlockhart submitted a review, later dismissed

2023-07-12 19:01 UTC, jaredlockhart commented on .circleci/config.yml
> +            docker push ${DOCKERHUB_CIRRUS_REPO}:latest
Couple things

1) We don't need to push anything other than deploy, the only reason we push the other stages for experimenter is so in theory your local build can use the remote cache, which worked for a while then stopped and I haven't had time to go back and figure it out, so just build and push deploy here

2) We should be able to reuse all the existing environment variables except for repo, in theory we should be able to push to `mozilla/cirrus`, ie those creds should have permission to that org.  Give that a shot.

2023-07-13 00:31 UTC, yashikakhurana commented
okay also I have added the environment variable- https://app.circleci.com/settings/project/github/mozilla/experimenter/environment-variables

2023-07-13 14:44 UTC, jeddai commented on .circleci/config.yml
> +            make cirrus_build cirrus_test
Should this be cirrus_build_prod maybe? It looks like that's what actually builds and tags as `cirrus:deploy` based on the Makefile. Also if we aren't pushing the test image and this job requires `Check Cirrus` I don't think we need to include the test here.
```suggestion
            make cirrus_build_prod
```

2023-07-13 15:57 UTC, jaredlockhart requested changes

2023-07-13 16:21 UTC, jeddai commented on .circleci/config.yml
> +              ignore:
I'm thinking this may have been left in for testing but we'll def want this to be `only` before merging.
```suggestion
              only:
```

2023-07-13 16:25 UTC, jeddai commented on .circleci/config.yml
> +              ignore:
Awesome just wanted to double check!

2023-07-13 16:27 UTC, jaredlockhart commented
Closing in favour of https://github.com/mozilla/experimenter/pull/9118

2023-07-13 16:27 UTC, closed without merging