fix #9073 feat(cirrus): Set value using glean metrics
mozilla/experimenter pull request #9115
Opened 2023-07-13 00:18 UTC by yashikakhurana

Because

- We want to set metrics and send pings

This commit

- Set metrics and sends pings using the defined `metrics.yaml` and `pings.yaml`
- Test cases to verify the changes

2023-07-13 05:38 UTC, travis79 approved these changes
This looks good to me. I did give one suggestion about just using `reset_glean` for initializing during tests but no need to block on that.

2023-07-13 05:38 UTC, travis79 commented on cirrus/server/tests/conftest.py
> +    return initialize_glean()
Resetting glean via the reset API also initializes Glean, so initializing it before a test could be accomplished by just calling that API. There is also an [optional parameter](https://github.com/mozilla/glean/blob/4198786204fa19c041bdefe7abb91ddc193747db/glean-core/python/glean/testing/__init__.py#L27) to the reset function if you need to re-initialize Glean without clearing the stored information.

2023-07-13 15:41 UTC, jeddai requested changes
This is looking great from a Glean SDK perspective! I have some comments about how it is set up to collate the Enrollment metrics from the partial config data but this is shaping up very nicely!

2023-07-13 15:41 UTC, jeddai commented on cirrus/server/cirrus/main.py
> +    return experiment_slug, branch_slug, enrollment_id, experiment_type
To collate the enrollment data into the data that should be sent through Glean you'll actually want it to iterate across all the enrollments, filter them down to only those with the `Enrolled` status, and return a list of enrollment extra dicts (or a specific type if you'd prefer).

```suggestion
def get_metrics_data(enrolled_partial_configuration: Dict[str, Any]):
    result = []
    enrollments = enrolled_partial_configuration.get("enrollments", [])
    
    for enrollment in enrollments:
        # Check if status is `Enrolled`
        # Find enrollment event in `events` to get enrollment uuid
        # Put together dict/object with values noted above
        # Append dict to `result`
        pass
        
    return result
```

2023-07-20 20:25 UTC, closed without merging

2023-07-20 20:26 UTC, yashikakhurana commented
closed in favor of https://github.com/mozilla/experimenter/pull/9140