Teach cirrus about coenrolling features
mozilla/experimenter pull request #9174
Opened 2023-07-25 18:13 UTC by jhugman

Fixes [EXP-3626](https://mozilla-hub.atlassian.net/browse/EXP-3626).

Because

- Coenrolling feature ids are required for constructing the Nimbus SDK, Cirrus is unable to run

This commit

- Gets the coenrolling feature ids from FML, and passes it to the SDK.

2023-07-25 19:11 UTC, yashikakhurana requested changes
overall looks good, can we add a test with the list of `coenrolling_features_ids`?

2023-07-25 19:12 UTC, yashikakhurana commented
and also some type needs to be defined, I am happy to help on this PR :)

2023-07-25 19:57 UTC, jaredlockhart commented
Yes please do @yashikakhurana 🎉

2023-07-26 05:32 UTC, yashikakhurana commented
@jaredlockhart @jhugman yup type definition done, cirrus check command should be green now :) , let me know if need any other help :)

2023-07-26 15:08 UTC, jaredlockhart approved these changes
LGTM thnx @jhugman @yashikakhurana ! 🎉 🎉 🎉

2023-07-26 17:44 UTC, yashikakhurana approved these changes
Thank you @jhugman 🎉

2023-07-26 17:44 UTC, yashikakhurana commented on cirrus/server/tests/test_sdk.py
> +    }
🎉

2023-07-26 18:52 UTC, merged