fixes #9122 bug(nimbus): limit multi-feature experiments to 20 features
mozilla/experimenter pull request #9187
Opened 2023-07-26 18:10 UTC by brennie

Because:
 - the namespace field has a character limit; and
 - adding arbitrarily many feature configs to an experiment will cause the limit to be hit

this commit:
 - increases the max length of NimbusIsolationGroup names to 2048; and
 - adds a limit of 10 features to the selected feature configs.

2023-07-26 19:50 UTC, yashikakhurana requested changes
overall looks good, just one minor comment regarding the CSS classes [bootstrap doc](https://react-bootstrap-v4.netlify.app/layout/grid/)

2023-07-26 19:50 UTC, yashikakhurana commented on experimenter/experimenter/nimbus-ui/src/styles/index.scss
> +
we can use bootstrap classes to achieve this and won't need to define CSS in here

2023-07-27 19:05 UTC, yashikakhurana approved these changes
thank you @brennie this looks perfect :)

2023-07-27 19:37 UTC, jaredlockhart approved these changes
Yep, tested locally, looks great, works great, thnx @brennie 🎉 🎉 🎉 🎉

2023-07-31 18:02 UTC, merged