For #9342 feat(project): Add configuration folder with yaml files for each mobile application
mozilla/experimenter pull request #9389
Opened 2023-09-11 20:10 UTC by eliserichards

Because

- We want to specify the following for each of the mobile apps:
   - repo link
   - path to the fml file for the repo
   - a mapping for the version tags (so that we can find the appropriate FML for a specific version)

This commit

- Adds a new folder, `/experimenter/features/configs` that contains a file for each mobile application
   - This locations--`/features`--also contains the feature definitions that map to the `NimbusFeature` API
- Adds files for: 
   - ios
   - focus ios
   - fenix
   - focus android

----
We don't need anything for Klar, do we?

2023-09-11 21:09 UTC, jaredlockhart reviewed
Should these be in separate yamls?  Or folded into the [application config constants](https://github.com/mozilla/experimenter/blob/main/experimenter/experimenter/experiments/constants.py#L60-L175)?  Where will these be consumed?

2023-09-12 16:42 UTC, jaredlockhart commented
Also I should've pointed out, right now these paths are [defined](https://github.com/mozilla/experimenter/blob/main/Makefile#L56-L60) and [consumed](https://github.com/mozilla/experimenter/blob/main/Makefile#L91-L95) directly in the Makefile, but as we add (many!) more applications, we'll want a more streamlined way to add and configure applications, which I believe is what this PR is driving towards, and to that effect one option is to move it all into Python space and then move the FML integration commands also into Python space as a management command filed here https://github.com/mozilla/experimenter/issues/9286, though I pre emptively filed that and it may not be the correct approach and I defer to to @brennie to decide on an effective strategy.

2023-09-12 17:21 UTC, brennie requested changes

2023-09-12 17:21 UTC, brennie commented on experimenter/experimenter/features/configs/fenix.yaml
> +  fmlPath: app/nimbus.fml.yaml
```suggestion
  repo: @mozilla-mobile/firefox-android
  fmlPath: fenix/app/nimbus.fml.yaml
```

2023-09-12 17:21 UTC, brennie commented on experimenter/experimenter/features/configs/focus-android.yaml
> +  fmlPath: app/nimbus.fml.yaml
```suggestion
  repo: @mozilla-mobile/firefox-android
  fmlPath: focus-android/app/nimbus.fml.yaml
```

2023-09-12 17:42 UTC, brennie approved these changes

2023-09-12 18:04 UTC, merged