chore(nimbus): Correct release branches for Fenix and Focus
mozilla/experimenter pull request #9394
Opened 2023-09-12 22:31 UTC by brennie

Because
- we want to keep track of repositories that we ingest FML files from
this commit
- corrects the branch names for Fenix and Focus browsers.

2023-09-12 23:19 UTC, eliserichards commented
I just commented this on the other PR: https://github.com/mozilla/experimenter/pull/9395#discussion_r1323735855. Not sure if we should be using the tags here so that we get all of the dot releases, or if we just want major releases (which use the `releases_v` format)

2023-09-13 17:02 UTC, jaredlockhart approved these changes
Neat!

2023-09-13 17:06 UTC, eliserichards requested changes
A few nits :D

2023-09-13 17:06 UTC, eliserichards commented on experimenter/experimenter/features/configs/apps.yaml
>  ios:
Was just chatting with @jhugman and realized these should be matching these [`app_names`](https://github.com/mozilla/experimenter/blob/36b973d502f765b698f7b16439fcf875492db10e/experimenter/experimenter/experiments/constants.py#L93) (not the slugs)
```suggestion
firefox_ios:
```

2023-09-13 17:06 UTC, eliserichards commented on experimenter/experimenter/features/configs/apps.yaml
>  focus-android:
```suggestion
focus_android:
```

2023-09-13 17:06 UTC, eliserichards commented on experimenter/experimenter/features/configs/apps.yaml
>  focus-ios:
```suggestion
focus_ios:
```

2023-09-13 17:06 UTC, eliserichards commented on experimenter/experimenter/features/configs/apps.yaml
> +  minor_release_tag: "fenix-v{major}.{minor}"
Fenix just has `v`, not the app name like focus does

```suggestion
  minor_release_tag: "v{major}.{minor}"
```

2023-09-13 17:40 UTC, eliserichards approved these changes
Awesome 👏

2023-09-13 17:52 UTC, merged