Replace queryByTestId with getByTestId
mozilla/experimenter pull request #9608
Opened 2023-10-18 09:06 UTC by WhiteNight110

I have completed the replacement of the corresponding code as required.

2023-10-18 17:04 UTC, eliserichards commented
@WhiteNight110 thanks for taking on this task! It looks like linting is failing with the following errors: 

```
/experimenter/experimenter/nimbus-ui/src/components/Summary/SummaryTimeline/index.test.tsx
  51:12  error  Replace `⏎······screen.getByTestId("label-enrollment-end-date"),⏎····` with `screen.getByTestId("label-enrollment-end-date")`  prettier/prettier
  89:12  error  Replace `⏎······screen.getByTestId("label-enrollment-end-date"),⏎····` with `screen.getByTestId("label-enrollment-end-date")`  prettier/prettier

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

You can fix those, and then run `make check` from the `experimenter` folder to see if there are any other errors to fix 👍

2023-10-19 21:44 UTC, brennie requested changes

2023-10-19 21:44 UTC, brennie commented on experimenter/experimenter/nimbus-ui/src/components/Summary/SummaryTimeline/index.test.tsx
> +      expect(screen.getByTestId("label-not-launched")).toBeInTheDocument();
You don't need expect().toBeInTheDocument(). The call to `getByTestId()` will throw if it cant find the element.

2023-10-19 21:44 UTC, brennie commented on experimenter/experimenter/nimbus-ui/src/components/Summary/SummaryTimeline/index.test.tsx
> +      expect(screen.getByTestId("label-release-date")).toBeNull();
This is incorrect. getByTestId throws if the element is not found and we are asserting this element does not exist. Revert this change

2023-10-19 21:44 UTC, brennie commented on experimenter/experimenter/nimbus-ui/src/components/Summary/SummaryTimeline/index.test.tsx
>        ).not.toBeInTheDocument();
This too.

2023-10-19 21:44 UTC, brennie commented on experimenter/experimenter/nimbus-ui/src/components/Summary/SummaryTimeline/index.test.tsx
> +      expect(screen.getByTestId("label-end-date")).not.toBeInTheDocument();
This too.

2023-10-19 21:44 UTC, brennie commented on experimenter/experimenter/nimbus-ui/src/components/Summary/SummaryTimeline/index.test.tsx
> +    expect(screen.getByTestId("label-not-launched")).not.toBeInTheDocument();
This too.

2023-10-19 21:44 UTC, brennie commented on experimenter/experimenter/nimbus-ui/src/components/Summary/SummaryTimeline/index.test.tsx
> +    expect(screen.getByTestId("label-not-launched")).not.toBeInTheDocument();
This too.

2023-10-31 05:51 UTC, WhiteNight110 commented
Sorry, I have been busy lately and may not be able to continue working

2023-11-01 17:55 UTC, jaredlockhart commented
@WhiteNight110 No problem, thank you for taking a stab at this, I will close this and if you get time in the future feel free to come back and reopen it or file a new PR 🙏

2023-11-01 17:55 UTC, closed without merging